\section{Errors and exception handling}
\begin{itemize}
    \item try: code that will be attempted. 
    \item except: in case of error this will be executed.
    \item finally: this will always be executed regardless of the error. 
\end{itemize}
\begin{minted}[autogobble]{python}
    def add(n1,n2):
        return n1 + n2 

    add(1,input("Num2:"))
    # output: error

    try:
        add(1,input("Num2:"))
    except:
        print("Error")
    else: 
        print("excecute if except is not excecuted")
    finally:
        print("Done")
\end{minted}


%----------------------------------------------------------------------------------------
\section{Pylint overview}
\begin{itemize}
    \item Unit testing: test your code, makes sure your code still works. 
    \item pylint \& unittest 
    \item PEP-8 unit testing convention. 
\end{itemize}
pylint: run on command line: 
\begin{Verbatim}[breaklines=true, breakanywhere=true]
pylint myfile.py 
\end{Verbatim}


%----------------------------------------------------------------------------------------
\section{unittest: run on command line:} 
in the cap.py file: 
\begin{minted}[autogobble]{python}
    def cap_text(text):
        return text.title()
\end{minted}
on test.py:
\begin{minted}[autogobble]{python}
    import unittest
    import cap 
    class TestCap(unittest.TestCase): 
        def test_one_word(self):
            text = "python"
            result = cap.cap_text(text)
            self.assertEqual(result,"Python")
        def test_multiple_words(self): 
            text = "monty python"
            result = cap.cap_text(text)
            self.assertEqual(result,"Monty Python")
    if __name__ == "__main__":
        unittest.main()
\end{minted}
